Repository jwt/ruby-jwt, pull requests merged in 2018-09, with the labels that each got.

#280 Add note about using a hard coded algorithm in README
  README.md
Labels: documentation, enhancement

#278 Add Appraisal support
  .gitignore
  .travis.yml
  Appraisals
  gemfiles/rails_5.0.gemfile
  gemfiles/rails_5.1.gemfile
  gemfiles/rails_5.2.gemfile
  gemfiles/standalone.gemfile
  ruby-jwt.gemspec
Labels: enhancement, feature

#285 Add RSASSA-PSS signature signing support
  README.md
  lib/jwt/algos/ps.rb
  lib/jwt/error.rb
  lib/jwt/security_utils.rb
  lib/jwt/signature.rb
  ruby-jwt.gemspec
  spec/integration/readme_examples_spec.rb
  spec/jwt_spec.rb
Labels: WIP, discussion, documentation, enhancement, feature, security
